### ISSUE TITLE
Parallel glmnet does not work

### ISSUE THREAD

**Issue by Zhuk66** [mschubert/clustermq#144]
```r
library(glmnet)
set.seed(1010)
n=1000;p=100
nzc=trunc(p/10)
x=matrix(rnorm(n*p),n,p)
beta=rnorm(nzc)
fx= x[,seq(nzc)] %*% beta
eps=rnorm(n)*5
y=drop(fx+eps)
px=exp(fx)
px=px/(1+px)
ly=rbinom(n=length(px),prob=px,size=1)
set.seed(1011)
clustermq::register_dopar_cmq(n_jobs=0)
cvob1=cv.glmnet(x,y, parallel=TRUE)

Submitting 10 worker jobs (ID: 6344) ... 
Running 10 calculations (7 objs/0 Mb common; 1 calls/chunk) ... 
[=======>------------------------------------------------------------]  10% (10/10 wrk) eta: 25s
Master: [3.1s 1.8% CPU]; Worker: [avg 99.1% CPU, max 289.0 Mb] 
Error in summarize_result(job_result, n_errors, n_warnings, cond_msgs,  :
    1/1 jobs failed (0 warnings). Stopping. (Error #1) object 'foldid' not found
```

This code works with doParallel or future.batchtools.

**Comment by mschubert** [comment]
Thank you for testing this!

First off: I will address this with #82, which will be part of the next release.

However, I think this is a bug in `glmnet` rather than `clustermq`. Their [parallel code](https://github.com/cran/glmnet/blob/master/R/cv.glmnet.R#L45) makes use of variables not defined in the environment, and it should list them in `.export` to make them available on workers.

Hence, the authors are relying on non-guaranteed behavior in `foreach` that is supported in with forking (because child threads will have access to the memory of the parent thread) and `future.batchtools` (because the package exports required globals automatically).

**Comment by mschubert** [comment]
Turns out this was my mistake and `foreach` actually provides an API to query these variables and export them automatically.

This is fixed in the latest *develop*.
