### ISSUE TITLE
Monitor sockets for disconnects

### ISSUE THREAD

**Issue by mschubert** [mschubert/clustermq#150]
There is a [zmq-socket-monitor](http://api.zeromq.org/4-1:zmq-socket-monitor) that can be used to detect disconnects of peers, e.g. when the workers shut down unexpectedly or are killed (checked this; the `FIN` TCP/IP package is still sent with `kill -9`)

This would make us much more robust to stalling because of worker crashes

The approach might replace #33

**Comment by mstr3336** [comment]
Hi @mschubert, I'm just wondering whether you're leaning more toward this or #33 , or whether these two approaches may work together? 

I know that  these two functionalities are part of the v0.9 roadmap, and since I use clustermq so much for work, I'm happy to put in some work towards the v0.9 roadmap, particularly timeout robustness, and fault tolerance.

**Comment by multimeric** [comment]
Hi, just wondering if this ever got implemented? I've had some jobs killed due to timeout etc and the master process doesn't seem to notice.

**Comment by mschubert** [comment]
It's implemented in `develop` but not usable yet:

https://github.com/mschubert/clustermq/blob/8fdb325bafbaa13a35c5349ed0cf476ee93f6837/src/CMQMaster.cpp#L73-L74

**Comment by multimeric** [comment]
That makes sense, thanks for the update!
