### ISSUE TITLE
How can I disable the progress bar ?

### ISSUE THREAD

**Issue by statquant** [mschubert/clustermq#167]
Hello, is there a way to disable the progress bar , if not would you kindly add an option like options(clustermq.progress = FALSE). I can PR if you point me to it

**Comment by mschubert** [comment]
Have you tried

```r
Q(... verbose=FALSE)?
```

`?Q` states

> verbose: Print status messages and progress bar (default: TRUE)

**Comment by statquant** [comment]
Sorry I should have said that I use foreach

**Comment by mschubert** [comment]
Looks like currently your only option is to `suppressMessages()`, but we should probably support the `.verbose` argument in `foreach`.

Should be as simple as:

```diff
--- a/R/foreach.r
+++ b/R/foreach.r
@@ -56,7 +56,8 @@ cmq_foreach = function(obj, expr, envir, data) {
         data$pkgs = unique(c(data$pkgs, obj$packages))
     }

-    result = do.call(Q_rows, c(list(df=args_df, fun=fun), data))
+    result = do.call(Q_rows, c(list(df=args_df, fun=fun, verbose=obj$verbose),
+                               data))

     accum = foreach::makeAccum(it)
     accum(result, tags=seq_along(result))
```

Related: #164

**Comment by mschubert** [comment]
Applying the suggested patch above will not only print `clustermq` messages, but also low-level `foreach` messages.

I'd argue we are not interested in those.

I checked whether I could solve this with:

* Different levels of `.verbose`, e.g. `1` for `clustermq` messages and `2` for `foreach` messages. This does not work, because `foreach` checks that the type is `logical`
* By adding an additional `.progress` parameter to `foreach`, which does not work because it does not support `...`

Hence, if you want to suppress the progress bar, you can still wrap your call in `suppressMessages(...)`.
