### ISSUE TITLE
SLURM: "Illegal instruction" on some nodes

### ISSUE THREAD

**Issue by pat-s** [mschubert/clustermq#171]
On our HPC we have two partitions with different machines.
On one of them R does not start when being triggered via SLURM/clustermq and errors with

```
/var/spool/slurmd/job07159/slurm_script: line 13:  7333 Illegal instruction
```

"line 13" in this case is 

```
CMQ_AUTH={{ auth }} /opt/R/3.6.1/bin/R --no-save --no-restore -e 'clustermq:::worker("{{ master }}")'
```

I've tested this running a job on all partitions.
All R jobs work on one of them and fail on the other.

All nodes are running on the same virtual image and same architecture.
They differ in CPU/Mem and n_sockets, n_cores etc.
These differences are however declared in `slurm.conf`.

This is a shot in the wild but maybe you have some sort of idea what might be the reason for this? Searching the web lead me to nothing.

maybe related: 
- https://github.com/HenrikBengtsson/future.batchtools/issues/11
- https://github.com/ropensci/drake/issues/115

**Comment by mschubert** [comment]
Could it be that you're using different templates and the one that fails is missing a closing single quote `'`? (or this just got lost copy-pasting)

**Comment by michaelmayer2** [comment]
Not sure if this is actually a clustermq issue. 

To me it looks like your version of R was built on nodes with the same processor type and architecture you have in the partition clustermq works as expected. This processor type seems to be much more recent that the processor type in the other partition where clustermq crashes. 

Suggest you run an interactive session on the partition where clustermq fails and try to run R there (without even clustermq) - I am sure this also fails with illegal instructions. 

Solution would be to either rebuild R on a node of the other partition so that the compiler automatically optimizes for that architecture (and make it upwards compatible with the other one). Alternatively force the build of R to use only optimisations that are appropriate for the lowest common denominator in terms of cpu features in your environment (e.g. SSE4.1, 4.2, AVX, AVX512, ...) 

If you want to go the extra mile, you also could build R using an automated build system like EasyBuild or get Microsoft Open R. 

Another possibility could be that the base version of R (installed in /opt/R/3.6.1) works fine on both partitions. You however may have installed clustermq as a custom R package in your user-specifc local .libPath() and implicitly build an optimized clustermq package (or any missing dependency) for this processor type again rendering it incompatible with the other partition with an (presumed) different/older processor type. The solution here would again either be to rebuild clustermq (and dependencies) in the other partition or configure R to build and optimize only for the lowese common denominator of cpu features.

**Comment by pat-s** [comment]
> To me it looks like your version of R was built on nodes with the same processor type and architecture you have in the partition clustermq works as expected.

Yes. Built from source on the working partition.

> This processor type seems to be much more recent that the processor type in the other partition where clustermq crashes.

True.

> Suggest you run an interactive session on the partition where clustermq fails and try to run R there (without even clustermq) - I am sure this also fails with illegal instructions.

I tried this already and it works.


> Solution would be to either rebuild R on a node of the other partition so that the compiler automatically optimizes for that architecture (and make it upwards compatible with the other one). 

Since I share R from the master node to all others via nfs, this is not possible.

> Alternatively force the build of R to use only optimisations that are appropriate for the lowest common denominator in terms of cpu features in your environment (e.g. SSE4.1, 4.2, AVX, AVX512, ...)

Even though I do not understand the acronyms, this make sense. Probably the issue comes from there.

>  implicitly build an optimized clustermq package (or any missing dependency) for this processor type again rendering it incompatible with the other partition with an (presumed) different/older processor type.

This could be the case, yes.

> If you want to go the extra mile, you also could build R using an automated build system like EasyBuild or get Microsoft Open R.

We use Spack already and only because we had some issues in the past with the R interpreters built by Spack and RStudio Server I decided to built R from source. 
Using the env module built by Spack works 🎉 

Thanks a ton!
