### ISSUE TITLE
clustermq falsely claims to submit jobs when running in local mode

### ISSUE THREAD

**Issue by dapritchard** [mschubert/clustermq#196]
Thank you so much for this package.  I've started it as a parallel backend for a drake pipeline, and have been very impressed over the performance improvements that I've observed. I'm interested in evaluating the use of clustermq / rzmq in settings outside of drake, but seemingly can't get the example using foreach listed in the User Guide (in the subsection titled "As parallel foreach backend") to work. What am I missing here?

In the example below on my 4-core machine, I would expect the following code to run in close to 5 seconds, yet it runs in close to 20 seconds. When I use similar code to run some heavy processing, I'm only observing one core doing significant work.

```r
library(foreach)
(n_cores <- parallel::detectCores())
#> [1] 4
clustermq::register_dopar_cmq(n_jobs = n_cores)
system.time(foreach(i = seq_len(n_cores)) %dopar% Sys.sleep(5))
#> Submitting 4 worker jobs (ID: 6856) ...
#>    user  system elapsed 
#>   0.118   0.022  20.187
```

(Note that the text of this issue is copied from a Stack Overflow question: https://stackoverflow.com/questions/62134030/using-clustermq-r-package-as-a-parallel-backend-for-foreach).

**Comment by mschubert** [comment]
Are you using the `local` instead of the `multicore` backend?

If so, the following should fix it:

```r
getOption("clustermq.scheduler") # check which scheduler is set
options(clustermq.scheduler = "multicore") # select multicore
# foreach example..
```

The reason for this is that we never select `multicore` automatically: it's bad locally because it may duplicate memory (and crash your computer), and it's bad on a computing cluster because it may exceed the number of cores you reserved.

When you load `library(clustermq)` and haven't set up your scheduler, it will tell you this:

> Option 'clustermq.scheduler' not set, defaulting to ‘LOCAL’
> --- see: https://mschubert.github.io/clustermq/articles/userguide.html#configuration

In your case it won't because you access the package namespace via `clustermq::`, and printing messages with accessing the namespace only is considered bad practice by CRAN.

But I can see how this is confusing, it should probably be more obvious than it is right now.

**Comment by mschubert** [comment]
I'd be happy to take a PR. I suggest 1 and 3:

1. Add a comment line [here](https://github.com/mschubert/clustermq/blob/master/vignettes/userguide.Rmd#L219-L220): `# set up the scheduler first, otherwise this will run sequentially`
2. Renaming the "LOCAL" scheduler is a no go because it would break existing user setups. Adding a special case for [the message](https://github.com/mschubert/clustermq/blob/master/R/zzz.r#L28) would work
3. Easiest would be to check `qsys$id` in [workers.r](https://github.com/mschubert/clustermq/blob/master/R/workers.r#L29-L30), but it would probably be better to somehow handle this in the `qsys`'s
