### ISSUE TITLE
Consider submitting to rOpenSci

### ISSUE THREAD

**Issue by wlandau** [mschubert/clustermq#94]
With [`rzmq`](https://github.com/ropensci/rzmq) as precedent, I think `clustermq` would be an excellent addition. Ref: https://github.com/ropensci/onboarding

**Comment by wlandau** [comment]
I just talked to the rOpenSci editors. Apparently, HPC packages do not fall in scope, and `rzmq` was a special case. Sorry if I got your hopes up.

**Comment by karthik** [comment]
Sorry @wlandau I can provide some backstory regarding `rzmq`. Back in 2014 we were trying to build a R kernel for the Jupyter notebook.  Jupyter uses `zmq` as their protocol and so we needed `rzmq` as a dependency. The authors at that time were not able to maintain this dependency (if I recall correctly), so we have to move it to `ropensci` in order to make IRkernel work.  It was before we set scope for our packages and it also pre dates the onboarding process. Irkernel has now moved to its own organization and we probably don't need rzmq here anymore. Thanks for checking in.

**Comment by mschubert** [comment]
No worries both

**Comment by wlandau** [comment]
Thank you for explaining, Karthik.
